version: '0.2'

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "instalando dependencias...."
      - cd "$CODEBUILD_SRC_DIR"
      - pwd
      - ls -la package*.json
      - echo "Verificando contenido del package.json:"
      - head -20 package.json
      - echo "Verificando inicio del package-lock.json:"
      - head -20 package-lock.json
      - node -v
      - npm -v
      - echo "Limpiando posibles caches..."
      - rm -rf node_modules package-lock.json 2>/dev/null || true
      - echo "Instalando desde cero..."
      - npm install --verbose
  pre_build:
    commands:
      - echo "ejecutando pruebas...."
      - cd "$CODEBUILD_SRC_DIR"
      - pwd
      - npm test --color
  build:
    commands:
      - echo "construyendo la aplicacion...."
      - cd "$CODEBUILD_SRC_DIR"
      - zip -r code.zip .
  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - '**/*'
    - code.zip
  discard-paths: yes