version: '0.2'

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "instalando dependencias...."
      - cd "$CODEBUILD_SRC_DIR"
      - pwd
      - node -v
      - npm -v
      - npm ci
  pre_build:
    commands:
      - echo "ejecutando pruebas...."
      - cd "$CODEBUILD_SRC_DIR"
      - pwd
      - npm test --color
  build:
    commands:
      - echo "construyendo la aplicacion...."
      - cd "$CODEBUILD_SRC_DIR"
      - zip -r code.zip .
  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - '**/*'
    - code.zip
  discard-paths: yes