version: '0.2'

phases:
  install:
    commands:
      - echo "instalando dependencias...."
      - npm install
  pre_build:
    commands:
      - echo "ejecutando pruebas...."
      - npm test
  build:
    commands:
      - echo "construyendo la aplicacion...."
      - zip -r code.zip .
  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - '**/*'
    - code.zip
  discard-paths: yes