version: '0.2'

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - 'cd "$CODEBUILD_SRC_DIR"'
      - 'if [ ! -f package.json ]; then echo "ERROR: package.json no encontrado en $CODEBUILD_SRC_DIR. Revisa la fuente del proyecto CodeBuild (CICD-Porject05)."; exit 2; fi'
      - 'if [ ! -f index.js ]; then echo "ERROR: index.js no encontrado. Asegura que el repositorio correcto se esté utilizando como fuente."; exit 2; fi'
      - 'node -v'
      - 'npm -v'
      - 'npm install --no-audit --no-fund'
  pre_build:
    commands:
      - 'npm test --color'
  build:
    commands:
      - 'zip -rq code.zip . -x "node_modules/*" -x ".git/*"'
  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - code.zip
  discard-paths: yes